Description: >
    This template contains the security groups required by our entire stack.
    We create them in a separate nested template, so they can be referenced
    by all of the other nested templates.

Parameters:

    EnvironmentName:
        Description: An environment name that will be prefixed to resource names
        Type: String

Resources:

    # This security group defines who/where is allowed to access the ECS hosts directly.
    # By default we're just allowing access from the load balancer.  If you want to SSH
    # into the hosts, or expose non-load balanced services you can open their ports here.
    ECSHostSecurityGroup:
        Type: AWS::EC2::SecurityGroup
        Properties:
            VpcId:
              Fn::ImportValue:
               !Sub "${EnvironmentName}-VPC"
            GroupDescription: Access to the ECS hosts and the tasks/containers that run on them
            SecurityGroupIngress:
                # Only allow inbound access to ECS from the same VPC
                - IpProtocol: -1
                  FromPort: '0'
                  ToPort: '0'
                  CidrIp:
                      Fn::ImportValue: !Sub "${EnvironmentName}-VpcCIDR"
            Tags:
                - Key: Name
                  Value: !Sub ${EnvironmentName}-ECS-Hosts
                - Key: CloudFormation
                  Value: true

Outputs:

    ECSHostSecurityGroup:
        Description: A reference to the security group for ECS hosts
        Value: !Ref ECSHostSecurityGroup
        Export:
            Name:  !Sub ${EnvironmentName}-ECSHostSecurityGroup
